// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: registry.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Channel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CsvName       string                 `protobuf:"bytes,2,opt,name=csvName,proto3" json:"csvName,omitempty"`
	Deprecation   *Deprecation           `protobuf:"bytes,3,opt,name=deprecation,proto3" json:"deprecation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetCsvName() string {
	if x != nil {
		return x.CsvName
	}
	return ""
}

func (x *Channel) GetDeprecation() *Deprecation {
	if x != nil {
		return x.Deprecation
	}
	return nil
}

type PackageName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageName) Reset() {
	*x = PackageName{}
	mi := &file_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageName) ProtoMessage() {}

func (x *PackageName) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageName.ProtoReflect.Descriptor instead.
func (*PackageName) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{1}
}

func (x *PackageName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Package struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Channels           []*Channel             `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	DefaultChannelName string                 `protobuf:"bytes,3,opt,name=defaultChannelName,proto3" json:"defaultChannelName,omitempty"`
	Deprecation        *Deprecation           `protobuf:"bytes,4,opt,name=deprecation,proto3" json:"deprecation,omitempty"`
	VersionLifecycles  []*VersionLifecycle    `protobuf:"bytes,5,rep,name=versionLifecycles,proto3" json:"versionLifecycles,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{2}
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *Package) GetDefaultChannelName() string {
	if x != nil {
		return x.DefaultChannelName
	}
	return ""
}

func (x *Package) GetDeprecation() *Deprecation {
	if x != nil {
		return x.Deprecation
	}
	return nil
}

func (x *Package) GetVersionLifecycles() []*VersionLifecycle {
	if x != nil {
		return x.VersionLifecycles
	}
	return nil
}

type GroupVersionKind struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Plural        string                 `protobuf:"bytes,4,opt,name=plural,proto3" json:"plural,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupVersionKind) Reset() {
	*x = GroupVersionKind{}
	mi := &file_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupVersionKind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupVersionKind) ProtoMessage() {}

func (x *GroupVersionKind) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupVersionKind.ProtoReflect.Descriptor instead.
func (*GroupVersionKind) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{3}
}

func (x *GroupVersionKind) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GroupVersionKind) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GroupVersionKind) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GroupVersionKind) GetPlural() string {
	if x != nil {
		return x.Plural
	}
	return ""
}

type Dependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{4}
}

func (x *Dependency) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Dependency) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Property struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{5}
}

func (x *Property) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Property) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Bundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsvName       string                 `protobuf:"bytes,1,opt,name=csvName,proto3" json:"csvName,omitempty"`
	PackageName   string                 `protobuf:"bytes,2,opt,name=packageName,proto3" json:"packageName,omitempty"`
	ChannelName   string                 `protobuf:"bytes,3,opt,name=channelName,proto3" json:"channelName,omitempty"`
	CsvJson       string                 `protobuf:"bytes,4,opt,name=csvJson,proto3" json:"csvJson,omitempty"`
	Object        []string               `protobuf:"bytes,5,rep,name=object,proto3" json:"object,omitempty"`
	BundlePath    string                 `protobuf:"bytes,6,opt,name=bundlePath,proto3" json:"bundlePath,omitempty"`
	ProvidedApis  []*GroupVersionKind    `protobuf:"bytes,7,rep,name=providedApis,proto3" json:"providedApis,omitempty"`
	RequiredApis  []*GroupVersionKind    `protobuf:"bytes,8,rep,name=requiredApis,proto3" json:"requiredApis,omitempty"`
	Version       string                 `protobuf:"bytes,9,opt,name=version,proto3" json:"version,omitempty"`
	SkipRange     string                 `protobuf:"bytes,10,opt,name=skipRange,proto3" json:"skipRange,omitempty"`
	Dependencies  []*Dependency          `protobuf:"bytes,11,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Properties    []*Property            `protobuf:"bytes,12,rep,name=properties,proto3" json:"properties,omitempty"`
	Replaces      string                 `protobuf:"bytes,13,opt,name=replaces,proto3" json:"replaces,omitempty"`
	Skips         []string               `protobuf:"bytes,14,rep,name=skips,proto3" json:"skips,omitempty"`
	Deprecation   *Deprecation           `protobuf:"bytes,15,opt,name=deprecation,proto3" json:"deprecation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bundle) Reset() {
	*x = Bundle{}
	mi := &file_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundle) ProtoMessage() {}

func (x *Bundle) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundle.ProtoReflect.Descriptor instead.
func (*Bundle) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{6}
}

func (x *Bundle) GetCsvName() string {
	if x != nil {
		return x.CsvName
	}
	return ""
}

func (x *Bundle) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *Bundle) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *Bundle) GetCsvJson() string {
	if x != nil {
		return x.CsvJson
	}
	return ""
}

func (x *Bundle) GetObject() []string {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *Bundle) GetBundlePath() string {
	if x != nil {
		return x.BundlePath
	}
	return ""
}

func (x *Bundle) GetProvidedApis() []*GroupVersionKind {
	if x != nil {
		return x.ProvidedApis
	}
	return nil
}

func (x *Bundle) GetRequiredApis() []*GroupVersionKind {
	if x != nil {
		return x.RequiredApis
	}
	return nil
}

func (x *Bundle) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Bundle) GetSkipRange() string {
	if x != nil {
		return x.SkipRange
	}
	return ""
}

func (x *Bundle) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *Bundle) GetProperties() []*Property {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Bundle) GetReplaces() string {
	if x != nil {
		return x.Replaces
	}
	return ""
}

func (x *Bundle) GetSkips() []string {
	if x != nil {
		return x.Skips
	}
	return nil
}

func (x *Bundle) GetDeprecation() *Deprecation {
	if x != nil {
		return x.Deprecation
	}
	return nil
}

type ChannelEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageName   string                 `protobuf:"bytes,1,opt,name=packageName,proto3" json:"packageName,omitempty"`
	ChannelName   string                 `protobuf:"bytes,2,opt,name=channelName,proto3" json:"channelName,omitempty"`
	BundleName    string                 `protobuf:"bytes,3,opt,name=bundleName,proto3" json:"bundleName,omitempty"`
	Replaces      string                 `protobuf:"bytes,4,opt,name=replaces,proto3" json:"replaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelEntry) Reset() {
	*x = ChannelEntry{}
	mi := &file_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelEntry) ProtoMessage() {}

func (x *ChannelEntry) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelEntry.ProtoReflect.Descriptor instead.
func (*ChannelEntry) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{7}
}

func (x *ChannelEntry) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *ChannelEntry) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *ChannelEntry) GetBundleName() string {
	if x != nil {
		return x.BundleName
	}
	return ""
}

func (x *ChannelEntry) GetReplaces() string {
	if x != nil {
		return x.Replaces
	}
	return ""
}

type ListPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackageRequest) Reset() {
	*x = ListPackageRequest{}
	mi := &file_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackageRequest) ProtoMessage() {}

func (x *ListPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackageRequest.ProtoReflect.Descriptor instead.
func (*ListPackageRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{8}
}

type ListBundlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBundlesRequest) Reset() {
	*x = ListBundlesRequest{}
	mi := &file_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBundlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBundlesRequest) ProtoMessage() {}

func (x *ListBundlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBundlesRequest.ProtoReflect.Descriptor instead.
func (*ListBundlesRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{9}
}

type GetPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPackageRequest) Reset() {
	*x = GetPackageRequest{}
	mi := &file_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPackageRequest) ProtoMessage() {}

func (x *GetPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPackageRequest.ProtoReflect.Descriptor instead.
func (*GetPackageRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{10}
}

func (x *GetPackageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PkgName       string                 `protobuf:"bytes,1,opt,name=pkgName,proto3" json:"pkgName,omitempty"`
	ChannelName   string                 `protobuf:"bytes,2,opt,name=channelName,proto3" json:"channelName,omitempty"`
	CsvName       string                 `protobuf:"bytes,3,opt,name=csvName,proto3" json:"csvName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBundleRequest) Reset() {
	*x = GetBundleRequest{}
	mi := &file_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBundleRequest) ProtoMessage() {}

func (x *GetBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBundleRequest.ProtoReflect.Descriptor instead.
func (*GetBundleRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{11}
}

func (x *GetBundleRequest) GetPkgName() string {
	if x != nil {
		return x.PkgName
	}
	return ""
}

func (x *GetBundleRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *GetBundleRequest) GetCsvName() string {
	if x != nil {
		return x.CsvName
	}
	return ""
}

type GetBundleInChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PkgName       string                 `protobuf:"bytes,1,opt,name=pkgName,proto3" json:"pkgName,omitempty"`
	ChannelName   string                 `protobuf:"bytes,2,opt,name=channelName,proto3" json:"channelName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBundleInChannelRequest) Reset() {
	*x = GetBundleInChannelRequest{}
	mi := &file_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBundleInChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBundleInChannelRequest) ProtoMessage() {}

func (x *GetBundleInChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBundleInChannelRequest.ProtoReflect.Descriptor instead.
func (*GetBundleInChannelRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{12}
}

func (x *GetBundleInChannelRequest) GetPkgName() string {
	if x != nil {
		return x.PkgName
	}
	return ""
}

func (x *GetBundleInChannelRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

type GetAllReplacementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsvName       string                 `protobuf:"bytes,1,opt,name=csvName,proto3" json:"csvName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllReplacementsRequest) Reset() {
	*x = GetAllReplacementsRequest{}
	mi := &file_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllReplacementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllReplacementsRequest) ProtoMessage() {}

func (x *GetAllReplacementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllReplacementsRequest.ProtoReflect.Descriptor instead.
func (*GetAllReplacementsRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{13}
}

func (x *GetAllReplacementsRequest) GetCsvName() string {
	if x != nil {
		return x.CsvName
	}
	return ""
}

type GetReplacementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsvName       string                 `protobuf:"bytes,1,opt,name=csvName,proto3" json:"csvName,omitempty"`
	PkgName       string                 `protobuf:"bytes,2,opt,name=pkgName,proto3" json:"pkgName,omitempty"`
	ChannelName   string                 `protobuf:"bytes,3,opt,name=channelName,proto3" json:"channelName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplacementRequest) Reset() {
	*x = GetReplacementRequest{}
	mi := &file_registry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplacementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplacementRequest) ProtoMessage() {}

func (x *GetReplacementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplacementRequest.ProtoReflect.Descriptor instead.
func (*GetReplacementRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{14}
}

func (x *GetReplacementRequest) GetCsvName() string {
	if x != nil {
		return x.CsvName
	}
	return ""
}

func (x *GetReplacementRequest) GetPkgName() string {
	if x != nil {
		return x.PkgName
	}
	return ""
}

func (x *GetReplacementRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

type GetAllProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Plural        string                 `protobuf:"bytes,4,opt,name=plural,proto3" json:"plural,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllProvidersRequest) Reset() {
	*x = GetAllProvidersRequest{}
	mi := &file_registry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProvidersRequest) ProtoMessage() {}

func (x *GetAllProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProvidersRequest.ProtoReflect.Descriptor instead.
func (*GetAllProvidersRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{15}
}

func (x *GetAllProvidersRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetAllProvidersRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetAllProvidersRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetAllProvidersRequest) GetPlural() string {
	if x != nil {
		return x.Plural
	}
	return ""
}

type GetLatestProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Plural        string                 `protobuf:"bytes,4,opt,name=plural,proto3" json:"plural,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestProvidersRequest) Reset() {
	*x = GetLatestProvidersRequest{}
	mi := &file_registry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestProvidersRequest) ProtoMessage() {}

func (x *GetLatestProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestProvidersRequest.ProtoReflect.Descriptor instead.
func (*GetLatestProvidersRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{16}
}

func (x *GetLatestProvidersRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetLatestProvidersRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetLatestProvidersRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetLatestProvidersRequest) GetPlural() string {
	if x != nil {
		return x.Plural
	}
	return ""
}

type GetDefaultProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Plural        string                 `protobuf:"bytes,4,opt,name=plural,proto3" json:"plural,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefaultProviderRequest) Reset() {
	*x = GetDefaultProviderRequest{}
	mi := &file_registry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultProviderRequest) ProtoMessage() {}

func (x *GetDefaultProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultProviderRequest.ProtoReflect.Descriptor instead.
func (*GetDefaultProviderRequest) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{17}
}

func (x *GetDefaultProviderRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetDefaultProviderRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetDefaultProviderRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetDefaultProviderRequest) GetPlural() string {
	if x != nil {
		return x.Plural
	}
	return ""
}

type Deprecation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deprecation) Reset() {
	*x = Deprecation{}
	mi := &file_registry_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deprecation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deprecation) ProtoMessage() {}

func (x *Deprecation) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deprecation.ProtoReflect.Descriptor instead.
func (*Deprecation) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{18}
}

func (x *Deprecation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VersionLifecycle struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Version       string                   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Compatibility []*PlatformCompatibility `protobuf:"bytes,2,rep,name=compatibility,proto3" json:"compatibility,omitempty"`
	Phases        []*LifecyclePhase        `protobuf:"bytes,3,rep,name=phases,proto3" json:"phases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionLifecycle) Reset() {
	*x = VersionLifecycle{}
	mi := &file_registry_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionLifecycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionLifecycle) ProtoMessage() {}

func (x *VersionLifecycle) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionLifecycle.ProtoReflect.Descriptor instead.
func (*VersionLifecycle) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{19}
}

func (x *VersionLifecycle) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionLifecycle) GetCompatibility() []*PlatformCompatibility {
	if x != nil {
		return x.Compatibility
	}
	return nil
}

func (x *VersionLifecycle) GetPhases() []*LifecyclePhase {
	if x != nil {
		return x.Phases
	}
	return nil
}

type PlatformCompatibility struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Versions      []string               `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformCompatibility) Reset() {
	*x = PlatformCompatibility{}
	mi := &file_registry_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformCompatibility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformCompatibility) ProtoMessage() {}

func (x *PlatformCompatibility) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformCompatibility.ProtoReflect.Descriptor instead.
func (*PlatformCompatibility) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{20}
}

func (x *PlatformCompatibility) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PlatformCompatibility) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

type LifecyclePhase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecyclePhase) Reset() {
	*x = LifecyclePhase{}
	mi := &file_registry_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecyclePhase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecyclePhase) ProtoMessage() {}

func (x *LifecyclePhase) ProtoReflect() protoreflect.Message {
	mi := &file_registry_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecyclePhase.ProtoReflect.Descriptor instead.
func (*LifecyclePhase) Descriptor() ([]byte, []int) {
	return file_registry_proto_rawDescGZIP(), []int{21}
}

func (x *LifecyclePhase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LifecyclePhase) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *LifecyclePhase) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

var File_registry_proto protoreflect.FileDescriptor

const file_registry_proto_rawDesc = "" +
	"\n" +
	"\x0eregistry.proto\x12\x03api\"k\n" +
	"\aChannel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acsvName\x18\x02 \x01(\tR\acsvName\x122\n" +
	"\vdeprecation\x18\x03 \x01(\v2\x10.api.DeprecationR\vdeprecation\"!\n" +
	"\vPackageName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xf0\x01\n" +
	"\aPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\bchannels\x18\x02 \x03(\v2\f.api.ChannelR\bchannels\x12.\n" +
	"\x12defaultChannelName\x18\x03 \x01(\tR\x12defaultChannelName\x122\n" +
	"\vdeprecation\x18\x04 \x01(\v2\x10.api.DeprecationR\vdeprecation\x12C\n" +
	"\x11versionLifecycles\x18\x05 \x03(\v2\x15.api.VersionLifecycleR\x11versionLifecycles\"n\n" +
	"\x10GroupVersionKind\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x16\n" +
	"\x06plural\x18\x04 \x01(\tR\x06plural\"6\n" +
	"\n" +
	"Dependency\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"4\n" +
	"\bProperty\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xb0\x04\n" +
	"\x06Bundle\x12\x18\n" +
	"\acsvName\x18\x01 \x01(\tR\acsvName\x12 \n" +
	"\vpackageName\x18\x02 \x01(\tR\vpackageName\x12 \n" +
	"\vchannelName\x18\x03 \x01(\tR\vchannelName\x12\x18\n" +
	"\acsvJson\x18\x04 \x01(\tR\acsvJson\x12\x16\n" +
	"\x06object\x18\x05 \x03(\tR\x06object\x12\x1e\n" +
	"\n" +
	"bundlePath\x18\x06 \x01(\tR\n" +
	"bundlePath\x129\n" +
	"\fprovidedApis\x18\a \x03(\v2\x15.api.GroupVersionKindR\fprovidedApis\x129\n" +
	"\frequiredApis\x18\b \x03(\v2\x15.api.GroupVersionKindR\frequiredApis\x12\x18\n" +
	"\aversion\x18\t \x01(\tR\aversion\x12\x1c\n" +
	"\tskipRange\x18\n" +
	" \x01(\tR\tskipRange\x123\n" +
	"\fdependencies\x18\v \x03(\v2\x0f.api.DependencyR\fdependencies\x12-\n" +
	"\n" +
	"properties\x18\f \x03(\v2\r.api.PropertyR\n" +
	"properties\x12\x1a\n" +
	"\breplaces\x18\r \x01(\tR\breplaces\x12\x14\n" +
	"\x05skips\x18\x0e \x03(\tR\x05skips\x122\n" +
	"\vdeprecation\x18\x0f \x01(\v2\x10.api.DeprecationR\vdeprecation\"\x8e\x01\n" +
	"\fChannelEntry\x12 \n" +
	"\vpackageName\x18\x01 \x01(\tR\vpackageName\x12 \n" +
	"\vchannelName\x18\x02 \x01(\tR\vchannelName\x12\x1e\n" +
	"\n" +
	"bundleName\x18\x03 \x01(\tR\n" +
	"bundleName\x12\x1a\n" +
	"\breplaces\x18\x04 \x01(\tR\breplaces\"\x14\n" +
	"\x12ListPackageRequest\"\x14\n" +
	"\x12ListBundlesRequest\"'\n" +
	"\x11GetPackageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"h\n" +
	"\x10GetBundleRequest\x12\x18\n" +
	"\apkgName\x18\x01 \x01(\tR\apkgName\x12 \n" +
	"\vchannelName\x18\x02 \x01(\tR\vchannelName\x12\x18\n" +
	"\acsvName\x18\x03 \x01(\tR\acsvName\"W\n" +
	"\x19GetBundleInChannelRequest\x12\x18\n" +
	"\apkgName\x18\x01 \x01(\tR\apkgName\x12 \n" +
	"\vchannelName\x18\x02 \x01(\tR\vchannelName\"5\n" +
	"\x19GetAllReplacementsRequest\x12\x18\n" +
	"\acsvName\x18\x01 \x01(\tR\acsvName\"m\n" +
	"\x15GetReplacementRequest\x12\x18\n" +
	"\acsvName\x18\x01 \x01(\tR\acsvName\x12\x18\n" +
	"\apkgName\x18\x02 \x01(\tR\apkgName\x12 \n" +
	"\vchannelName\x18\x03 \x01(\tR\vchannelName\"t\n" +
	"\x16GetAllProvidersRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x16\n" +
	"\x06plural\x18\x04 \x01(\tR\x06plural\"w\n" +
	"\x19GetLatestProvidersRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x16\n" +
	"\x06plural\x18\x04 \x01(\tR\x06plural\"w\n" +
	"\x19GetDefaultProviderRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x16\n" +
	"\x06plural\x18\x04 \x01(\tR\x06plural\"'\n" +
	"\vDeprecation\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x9b\x01\n" +
	"\x10VersionLifecycle\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12@\n" +
	"\rcompatibility\x18\x02 \x03(\v2\x1a.api.PlatformCompatibilityR\rcompatibility\x12+\n" +
	"\x06phases\x18\x03 \x03(\v2\x13.api.LifecyclePhaseR\x06phases\"O\n" +
	"\x15PlatformCompatibility\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1a\n" +
	"\bversions\x18\x02 \x03(\tR\bversions\"\\\n" +
	"\x0eLifecyclePhase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tstartDate\x18\x02 \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\x03 \x01(\tR\aendDate2\xcf\x05\n" +
	"\bRegistry\x12=\n" +
	"\fListPackages\x12\x17.api.ListPackageRequest\x1a\x10.api.PackageName\"\x000\x01\x124\n" +
	"\n" +
	"GetPackage\x12\x16.api.GetPackageRequest\x1a\f.api.Package\"\x00\x121\n" +
	"\tGetBundle\x12\x15.api.GetBundleRequest\x1a\v.api.Bundle\"\x00\x12G\n" +
	"\x13GetBundleForChannel\x12\x1e.api.GetBundleInChannelRequest\x1a\v.api.Bundle\"\x03\x88\x02\x01\x12U\n" +
	"\x1cGetChannelEntriesThatReplace\x12\x1e.api.GetAllReplacementsRequest\x1a\x11.api.ChannelEntry\"\x000\x01\x12B\n" +
	"\x15GetBundleThatReplaces\x12\x1a.api.GetReplacementRequest\x1a\v.api.Bundle\"\x00\x12R\n" +
	"\x1cGetChannelEntriesThatProvide\x12\x1b.api.GetAllProvidersRequest\x1a\x11.api.ChannelEntry\"\x000\x01\x12[\n" +
	"\"GetLatestChannelEntriesThatProvide\x12\x1e.api.GetLatestProvidersRequest\x1a\x11.api.ChannelEntry\"\x000\x01\x12M\n" +
	"\x1cGetDefaultBundleThatProvides\x12\x1e.api.GetDefaultProviderRequest\x1a\v.api.Bundle\"\x00\x127\n" +
	"\vListBundles\x12\x17.api.ListBundlesRequest\x1a\v.api.Bundle\"\x000\x01B\aZ\x05.;apib\x06proto3"

var (
	file_registry_proto_rawDescOnce sync.Once
	file_registry_proto_rawDescData []byte
)

func file_registry_proto_rawDescGZIP() []byte {
	file_registry_proto_rawDescOnce.Do(func() {
		file_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)))
	})
	return file_registry_proto_rawDescData
}

var file_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_registry_proto_goTypes = []any{
	(*Channel)(nil),                   // 0: api.Channel
	(*PackageName)(nil),               // 1: api.PackageName
	(*Package)(nil),                   // 2: api.Package
	(*GroupVersionKind)(nil),          // 3: api.GroupVersionKind
	(*Dependency)(nil),                // 4: api.Dependency
	(*Property)(nil),                  // 5: api.Property
	(*Bundle)(nil),                    // 6: api.Bundle
	(*ChannelEntry)(nil),              // 7: api.ChannelEntry
	(*ListPackageRequest)(nil),        // 8: api.ListPackageRequest
	(*ListBundlesRequest)(nil),        // 9: api.ListBundlesRequest
	(*GetPackageRequest)(nil),         // 10: api.GetPackageRequest
	(*GetBundleRequest)(nil),          // 11: api.GetBundleRequest
	(*GetBundleInChannelRequest)(nil), // 12: api.GetBundleInChannelRequest
	(*GetAllReplacementsRequest)(nil), // 13: api.GetAllReplacementsRequest
	(*GetReplacementRequest)(nil),     // 14: api.GetReplacementRequest
	(*GetAllProvidersRequest)(nil),    // 15: api.GetAllProvidersRequest
	(*GetLatestProvidersRequest)(nil), // 16: api.GetLatestProvidersRequest
	(*GetDefaultProviderRequest)(nil), // 17: api.GetDefaultProviderRequest
	(*Deprecation)(nil),               // 18: api.Deprecation
	(*VersionLifecycle)(nil),          // 19: api.VersionLifecycle
	(*PlatformCompatibility)(nil),     // 20: api.PlatformCompatibility
	(*LifecyclePhase)(nil),            // 21: api.LifecyclePhase
}
var file_registry_proto_depIdxs = []int32{
	18, // 0: api.Channel.deprecation:type_name -> api.Deprecation
	0,  // 1: api.Package.channels:type_name -> api.Channel
	18, // 2: api.Package.deprecation:type_name -> api.Deprecation
	19, // 3: api.Package.versionLifecycles:type_name -> api.VersionLifecycle
	3,  // 4: api.Bundle.providedApis:type_name -> api.GroupVersionKind
	3,  // 5: api.Bundle.requiredApis:type_name -> api.GroupVersionKind
	4,  // 6: api.Bundle.dependencies:type_name -> api.Dependency
	5,  // 7: api.Bundle.properties:type_name -> api.Property
	18, // 8: api.Bundle.deprecation:type_name -> api.Deprecation
	20, // 9: api.VersionLifecycle.compatibility:type_name -> api.PlatformCompatibility
	21, // 10: api.VersionLifecycle.phases:type_name -> api.LifecyclePhase
	8,  // 11: api.Registry.ListPackages:input_type -> api.ListPackageRequest
	10, // 12: api.Registry.GetPackage:input_type -> api.GetPackageRequest
	11, // 13: api.Registry.GetBundle:input_type -> api.GetBundleRequest
	12, // 14: api.Registry.GetBundleForChannel:input_type -> api.GetBundleInChannelRequest
	13, // 15: api.Registry.GetChannelEntriesThatReplace:input_type -> api.GetAllReplacementsRequest
	14, // 16: api.Registry.GetBundleThatReplaces:input_type -> api.GetReplacementRequest
	15, // 17: api.Registry.GetChannelEntriesThatProvide:input_type -> api.GetAllProvidersRequest
	16, // 18: api.Registry.GetLatestChannelEntriesThatProvide:input_type -> api.GetLatestProvidersRequest
	17, // 19: api.Registry.GetDefaultBundleThatProvides:input_type -> api.GetDefaultProviderRequest
	9,  // 20: api.Registry.ListBundles:input_type -> api.ListBundlesRequest
	1,  // 21: api.Registry.ListPackages:output_type -> api.PackageName
	2,  // 22: api.Registry.GetPackage:output_type -> api.Package
	6,  // 23: api.Registry.GetBundle:output_type -> api.Bundle
	6,  // 24: api.Registry.GetBundleForChannel:output_type -> api.Bundle
	7,  // 25: api.Registry.GetChannelEntriesThatReplace:output_type -> api.ChannelEntry
	6,  // 26: api.Registry.GetBundleThatReplaces:output_type -> api.Bundle
	7,  // 27: api.Registry.GetChannelEntriesThatProvide:output_type -> api.ChannelEntry
	7,  // 28: api.Registry.GetLatestChannelEntriesThatProvide:output_type -> api.ChannelEntry
	6,  // 29: api.Registry.GetDefaultBundleThatProvides:output_type -> api.Bundle
	6,  // 30: api.Registry.ListBundles:output_type -> api.Bundle
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_registry_proto_init() }
func file_registry_proto_init() {
	if File_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_proto_rawDesc), len(file_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registry_proto_goTypes,
		DependencyIndexes: file_registry_proto_depIdxs,
		MessageInfos:      file_registry_proto_msgTypes,
	}.Build()
	File_registry_proto = out.File
	file_registry_proto_goTypes = nil
	file_registry_proto_depIdxs = nil
}
